// =============================================
// StaySphere – Mock Data Store
// Replace these with API calls in future
// =============================================

export const ROOMS = [
{
  id: 1,
  name: 'Single Room (Non-AC)',
  type: 'Single',
  floor: 1,
  capacity: 1,
  price: 4500,
  status: 'available',
  amenities: ['WiFi', 'Fan', 'Common Bath', 'Bed', 'Cupboard'],
  description: 'Simple single room suitable for students. Non-AC with basic furniture and shared bathroom. Good for budget stay.',
  images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww'],
  rating: 3.9,
  reviews: 6,
  roomNo: '102',
},
{
  id: 2,
  name: 'Single Room (AC)',
  type: 'Single',
  floor: 2,
  capacity: 1,
  price: 7500,
  status: 'available',
  amenities: ['WiFi', 'AC', 'Attached Bath', 'Bed', 'Study Table', 'Cupboard'],
  description: 'Comfortable AC single room with attached bathroom. Ideal for students or working individuals who want privacy.',
  images: ['https://plus.unsplash.com/premium_photo-1682093007363-b05f4c3dc932?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8UEclMjBzaW5nbGUlMjByb29tfGVufDB8fDB8fHww'],
  rating: 4.3,
  reviews: 10,
  roomNo: '210',
},
{
  id: 3,
  name: 'Double Sharing (Non-AC)',
  type: 'Double',
  floor: 2,
  capacity: 2,
  price: 5000,
  status: 'available',
  amenities: ['WiFi', 'Fan', 'Common Bath', 'Bed', 'Cupboard'],
  description: 'Budget-friendly double sharing room. Suitable for friends. Includes basic furniture and shared washroom.',
  images: ['https://images.unsplash.com/photo-1623625434462-e5e42318ae49?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aG9zdGVsfGVufDB8fDB8fHww'],
  rating: 4.0,
  reviews: 8,
  roomNo: '215',
},
{
  id: 4,
  name: 'Double Sharing (AC)',
  type: 'Double',
  floor: 3,
  capacity: 2,
  price: 9000,
  status: 'available',
  amenities: ['WiFi', 'AC', 'Attached Bath', 'Bed', 'Study Table', 'Cupboard'],
  description: 'Spacious AC double sharing room with attached bathroom. Good option for comfortable shared living.',
  images: ['https://images.unsplash.com/photo-1771276045965-aa5c1ddf15a9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGF5aW5nJTIwZ3Vlc3QlMjByb29tfGVufDB8fDB8fHww'],
  rating: 4.4,
  reviews: 11,
  roomNo: '305',
},
{
  id: 5,
  name: 'Triple Sharing Room',
  type: 'Triple',
  floor: 1,
  capacity: 3,
  price: 4000,
  status: 'available',
  amenities: ['WiFi', 'Fan', 'Common Bath', 'Bed', 'Cupboard', 'Water Cooler'],
  description: 'Triple sharing room for students looking for economical stay. Basic setup with all essential facilities.',
  images: ['https://media.istockphoto.com/id/1814658510/photo/roommates-talking-in-bedroom-at-hostel.webp?a=1&b=1&s=612x612&w=0&k=20&c=babUmyWpr-xNnQ1ArnrxSQHL5xcoxXTF3YsAH_UWtLc='],
  rating: 3.7,
  reviews: 7,
  roomNo: '108',
},
{
  id: 6,
  name: '4 Sharing Dorm Room',
  type: 'Dorm',
  floor: 1,
  capacity: 4,
  price: 3000,
  status: 'available',
  amenities: ['WiFi', 'Fan', 'Common Bath', 'Locker', 'Bed'],
  description: 'Affordable dorm room with 4 sharing. Best for students who want low-cost accommodation with basic amenities.',
  images: ['https://images.unsplash.com/photo-1709805619372-40de3f158e83?q=80&w=1495&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
  rating: 3.6,
  reviews: 13,
  roomNo: '110',
}
]

export const BOOKINGS = [
  {
    id: 'BK001',
    userId: 1,
    roomId: 1,
    roomName: 'Cozy Single Room',
    roomNo: '201',
    checkIn: '2025-02-01',
    checkOut: '2025-07-31',
    status: 'confirmed',
    totalAmount: 39000,
    paymentStatus: 'paid',
    createdAt: '2025-01-20',
  },
  {
    id: 'BK002',
    userId: 2,
    roomId: 2,
    roomName: 'Deluxe Double Sharing',
    roomNo: '304',
    checkIn: '2025-03-01',
    checkOut: '2025-08-31',
    status: 'pending',
    totalAmount: 28800,
    paymentStatus: 'pending',
    createdAt: '2025-02-15',
  },
  {
    id: 'BK003',
    userId: 1,
    roomId: 5,
    roomName: 'Comfort Single AC',
    roomNo: '406',
    checkIn: '2024-09-01',
    checkOut: '2024-12-31',
    status: 'cancelled',
    totalAmount: 32000,
    paymentStatus: 'refunded',
    createdAt: '2024-08-10',
  },
];

export const USERS = [
  { id: 1, name: 'Arjun Mehta', email: 'arjun@email.com', phone: '9876543210', role: 'resident', status: 'active', joinedAt: '2025-01-15', currentRoom: '201' },
  { id: 2, name: 'Priya Shah', email: 'priya@email.com', phone: '9876543211', role: 'resident', status: 'active', joinedAt: '2025-02-10', currentRoom: '304' },
  { id: 3, name: 'Rohit Desai', email: 'rohit@email.com', phone: '9876543212', role: 'resident', status: 'inactive', joinedAt: '2024-11-05', currentRoom: null },
  { id: 4, name: 'Sneha Patel', email: 'sneha@email.com', phone: '9876543213', role: 'resident', status: 'active', joinedAt: '2025-03-01', currentRoom: null },
];

export const STATS = {
  totalRooms: 6,
  availableRooms: 4,
  occupiedRooms: 2,
  totalUsers: 4,
  activeBookings: 1,
  pendingBookings: 1,
  monthlyRevenue: 67800,
  occupancyRate: 33,
};
